your_diary_pro/your_diary_app/urls.py
from django.conf.urls import url
from your_diary_app import views

app_name='app'
urlpatterns=[
    url(r'^register/$',views.register,name="register"),
    url(r'^login/$',views.user_login,name="user_login"),
    url(r'^write/$',views.write,name="write"),
    url(r'^view/$',views.view,name="view"),
    url(r'^diary/$',views.diary,name='diary')
]

your_diary_pro/your_diary_pro/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from your_diary_app import views
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^register/',include('your_diary_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout,name="logout"),
]

your_diary_pro/your_diary_app/models.py
from django.db import models
# Create your models here.
class Diary_Page(models.Model):
    name=models.CharField(max_length=256)
    date=models.DateField()
    title=models.CharField(max_length=10)
    note=models.CharField(max_length=5000)

    def __str__(self):
        return self.name

your_diary_pro/your_diary_app/forms.py
from django import forms
from django.contrib.auth.models import User
from your_diary_app.models import Diary_Page

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'username'
        self.fields['password'].widget.attrs['placeholder'] = 'password'
        self.fields['email'].widget.attrs['placeholder'] = 'email'
    class Meta():
        model=User
        fields=('username','email','password')

class Diary_Page_Form(forms.ModelForm):
    note=forms.CharField(widget=forms.Textarea)
    DATE_INPUT_FORMATS = ['%d-%m-%Y']
    date=forms.DateField(input_formats=DATE_INPUT_FORMATS)
    class Meta():
        model=Diary_Page
        fields=('name','date','title','note')

your_diary_pro/your_diary_app/views.py
from django.shortcuts import render
from your_diary_app.forms import UserForm
from your_diary_app.forms import Diary_Page_Form
from your_diary_app.models import Diary_Page
# Create your views here.
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request,'your_diary_app/index.html')



@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required()
def diary(request):
    return render(request,'your_diary_app/diary.html')

def register(request):
    registered=False

    if request.method=='POST':
        user_form=UserForm(data=request.POST)

        if user_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            registered=True
        else:
            print(user_form.errors)
    else:
        user_form=UserForm()
    return  render(request,'your_diary_app/register.html',{'registered':registered,'user_form':user_form})

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            global user_name
            user_name=username
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            return HttpResponse("invalid login")
    else:
        return render(request,'your_diary_app/login.html',{})

def write(request):

        if request.method=='POST':
            diary_form=Diary_Page_Form(data=request.POST)
            if diary_form.is_valid():
                diary_form.save()
                return HttpResponseRedirect(reverse('index'))
            else:
                print(diary_form.errors)
        else:
            diary_form=Diary_Page_Form()
        return  render(request,'your_diary_app/write.html',{'diary_form':diary_form})

def view(request):
    if request.method=="POST":
        date=request.POST.get('date')
        diary_note=Diary_Page.objects.filter(name=user_name,date=date)
        if diary_note:
            return render(request,'your_diary_app/view.html',{'date':diary_note[0].date,'title':diary_note[0].title,'note':diary_note[0].note})
        else:
            return HttpResponse("no content")

your_diary_pro/templates/your_diary_app/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>YOUR_DIARY</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static "CSS/style.css"%}"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
    	ul {margin:0}
    	ul li {float:left;}
    	ul li {
    		padding: 60px;
    		list-style:none;
    	}
      h2 {
        padding :40px;
      }
    	</style>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <h2 class="navbar-brand brand-name">
      <img class="img-responsive2" src="{% static "logo/logo.jpg" %}"/>
     </h2>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
 </button>
 <div class="collapse navbar-collapse" id="navbarSupportedContent">
   <ul class="navbar-nav mr-auto">
     <li class="nav-item active">
       <a class="nav-link" href="{% url 'index' %}"> Home <span class="sr-only">(current)</span></a>
     </li>

     <li class="nav-item">
       <a class="nav-link" href="{%url 'app:register'%}"> REGISTER </a>
     </li>

     {% if user.is_authenticated %}
      <li class="nav-item"><li><a class="nav-link" href="{% url 'logout'%}">LOGOUT (logged in as {{user.username}})</a></li></li>
      {% else %}
      <li class="nav-item"><li><a class="nav-link" href="{% url 'app:user_login' %}">LOGIN</a></li></li>
      {% endif %}
   </ul>
 </div>
</nav>
       <div class="container">
         {%block body_block%}
           <!-- include -->
         {%endblock%}

       </div>



  </body>
</html>

your_diary_pro/templates/your_diary_app/diary.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>diary</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static "CSS/style1.css"%}"/>
  </head>
  <body>
  <div class="main">
    <div class="form-style-3">
    <fieldset><strong><h1><legend>WELCOME TO YOUR DIARY</legend></h1></strong>
    <form class="" action="{%url 'app:view'%}" method="post">
      {%csrf_token%}
      <strong><label for="date">Search A Note By Date</label><strong>
      <br>
      <input type="date" name="date" data-date-format="yyyy-mm-dd">
    <input type="submit"  value="FIND">
    <br><br>
    </form>
      <a href="{% url 'app:write' %}">ADD A NOTE TO YOUR DIARY</a>
    </div>
  </fieldset>
</div>
</div>

</div>
  </body>
</html>

your_diary_pro/templates/your_diary_app/index.html
{%extends "your_diary_app/base.html"%}
{%block body_block%}
<div class="wrapper">
  {% if user.is_authenticated %}
  <a href="{% url 'app:diary' %}" class="myButton">ADD A NOTE TO YOUR DIARY</a>
  {%else%}
  <a href="{% url 'app:user_login' %}" class="myButton">ADD A NOTE TO YOUR DIARY</a>
  {%endif%}
</div>
 {%endblock%}

your_diary_pro/templates/your_diary_app/login.html
{%extends "your_diary_app/base.html"%}
 {%block body_block%}

 <div id="container-login">
        <div id="title">
            <i class="material-icons lock">lock</i> Login
        </div>
   <form action="{% url 'app:user_login'%}" method="post">
     {% csrf_token %}
     <div class="input">
                <div class="input-addon">
                    <i class="material-icons">face</i>
                </div>
                <input id="username" name='username' placeholder="Username" type="text" required class="validate" autocomplete="off">
            </div>

            <div class="clearfix"></div>

            <div class="input">
                <div class="input-addon">
                    <i class="material-icons">vpn_key</i>
                </div>
                <input id="password" name='password' placeholder="Password" type="password" required class="validate" autocomplete="off">
            </div>
            <br>
            <input type="submit" value="Log In" />
        </form>

        <div class="register">
             Don't have an account yet?
            <a href="{% url 'app:register'%}"><button id="register-link">Register here</button></a>
        </div>
    </div>

 {%endblock%}

your_diary_pro/templates/your_diary_app/register.html
{%extends "your_diary_app/base.html"%}

 {%block body_block%}
  {%if registered%}
  <div class="wrapper">
    <a href="{% url 'index'%}" class="myButton">THANK YOU FOR REGISTRING .......</a>
  </div>
   {%else%}
   <div id="container-register">
        <div id="title">
            <i class="material-icons lock">lock</i> Register
        </div>
   <form enctype="multipart/form-data" method="post">
     {% csrf_token %}
     <div class="input">
                <div class="input-addon">
                    <i class="material-icons">face</i>
                </div>
                {{user_form.username}}
            </div>
      <div class="clearfix"></div>
      <div class="input">
                <div class="input-addon">
                    <i class="material-icons">email</i>
                </div>
                {{user_form.email}}
            </div>
          <div class="clearfix"></div>
            <div class="input">
                      <div class="input-addon">
                          <i class="material-icons">vpn_key</i>
                      </div>
                      {{user_form.password}}
                  </div>

     <input type="submit"  value="REGISTER">
     </form>
     <div class="register">
            Do you already have an account?
            <a href="{% url 'app:user_login' %}"><button id="register-link">Log In here</button></a>
        </div>
 </div>
   {%endif%}
 {%endblock%}

your_diary_pro/templates/your_diary_app/view.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>view</title>
  </head>
  <body>
   <p>DATE :  {{date}}</p>
   <p>TITLE:{{title}}</p>
   <p>NOTE :{{note}}</p>
  </body>
</html>

your_diary_pro/templates/your_diary_app/write.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Diary_Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static "CSS/style2.css"%}"/>
  </head>
   <body>
     <div style="display: flex; justify-content: flex-end">
     <div class="main">
     <!-- <form  method="post"> -->
     <!-- {% csrf_token %} -->
     <!-- <strong><h3>{{diary_form.as_p}}</strong></h3> -->
     <!-- <input type="submit" name="" value="submit"> -->
   <!-- </form> -->
<div class="form-style-3">
<form method="post">
  {%csrf_token%}
<fieldset><legend>WRITE YOUR NOTE HERE (name should be your username)</legend>
   <span></span>{{diary_form.as_p}}
<label><span> </span><input type="submit" value="ADD TO YOUR DIARY" /></label>
</fieldset>
</form>

</div>
</div>
</div>
  </body>
</html>